<a href="https://colab.research.google.com/github/ledwabarefentse/Import_data/blob/main/ImportData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
from google.colab import files
uploades = files.upload()

Saving netflix_titles.csv to netflix_titles.csv

In [ ]:
global df
df0 = create_dataframe('netflix_titles.csv')
df0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/Attrition_RCA.csv", encoding = "latin-1")
df

,ï»¿Unique_Customer_Key,Start_Period,End_Period,Current_Balance,Instalment_Amount,Open_Balance,Overdue_Amount,Sub_Segment,Age_Ind,Core_Def,...,PREDICTED_EMPLOYER,SALARY_IND,PENSION_IND,INDUSTRY_OUTLOOK,Self_Employed_Ind,DDA_MNMM_Q1_MNMM_Q3_PCT,DDA_PRM_CRTO_BLNC_Q1_PCT,IDS_TOT_AGE_NR,AVERAGE_TRANSACTIONS,VSI
0,1,202102,202202,184865.0,8175.0,209462.0,0.0,e.Gold,ETB,b. Core,...,NaN,0.0,0.0,5. Unclassified,1.0,138,-287,2684,50.08,8
1,2,202102,202202,1276768.0,17037.0,1793922.0,0.0,a.Private Wealth,ETB,No Go,...,KROONDAL AUTO (PTY) LTD,0.0,0.0,4. Caution,1.0,-92929,1386,-91919,51.17,11
2,3,202102,202202,107947.0,2652.0,71140.0,47937.0,e.Gold,ETB,No Go,...,NaN,0.0,0.0,5. Unclassified,0.0,-683,7222,2778,15.08,4
3,4,202102,202202,51.0,51.0,3600.0,0.0,f.Easy,ETB,c. Care,...,NaN,0.0,0.0,5. Unclassified,0.0,198,1625,9015,8.75,3
4,5,202102,202202,241753.0,6633.0,508600.0,0.0,b.Private Clients,ETB,f. Missing,...,NaN,0.0,0.0,5. Unclassified,1.0,55,10,5420,11.50,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,149996,202102,202202,980.0,980.0,0.0,1540.0,f.Easy,RTB,f. Missing,...,BLINKWATER MEULE (PTY) LTD,1.0,0.0,1. Postive,0.0,-92929,-10364,151,3.83,2
149996,149997,202102,202202,6990.0,590.0,7893.0,0.0,e.Gold,RTB,d. Non Core,...,ADNAN MY FONE CELLULAR REPAIRS (PTY) LT,0.0,0.0,5. Unclassified,0.0,-92929,14063,151,16.50,3
149997,149998,202102,202202,11189.0,2098.0,20000.0,0.0,e.Gold,RTB,d. Non Core,...,DEPARTMENT OF EDUCATION,1.0,0.0,2. Neutral,0.0,-92929,-9560,151,7.00,3
149998,149999,202102,202202,NaN,NaN,NaN,NaN,f.Easy,RTB,b. Core,...,GAUTENG PROVINCIAL GOVERNMENT,0.0,0.0,1. Postive,0.0,-92929,16617,151,3.33,1
149999,150000,202102,202202,2900.0,2900.0,2900.0,2900.0,f.Easy,RTB,No Go,...,NaN,1.0,0.0,5. Unclassified,0.0,-92929,-6059,-91919,8.17,3

In [ ]:
df2 = pd.read_csv("/content/drive/MyDrive/Datasets/Employer_RCA.csv", encoding = "latin-1")
df2.head()

,ï»¿Unique_Customer_Key,Period,SALARY_IND,PENSION_IND,RAW_EMPLOYER_NAME,CLEANED_EMPLOYER_NAME,INDUSTRY_CATEGORY,INDUSTRY_SUB_CATEGORY,INDUSTRY_OUTLOOK,SALARY_AMOUNT,SUB_SEGMENT,MAIN_BANKED_IND,Account_Age,Age_Ind,no_go_ind,Risk_Class
0,1,202204,1,0,adcorp wokforce solutions,NaN,BUSINESS AND ADMINISTRATIVE,"RECRUITMENT, STAFFING AND EMPLOYMENT PLACEMENT",3. Negative,4032.99,f.Easy,Main Banked,126,RTB,0,f.Class 6
1,2,202204,1,0,adcorp wokforce solutions,NaN,BUSINESS AND ADMINISTRATIVE,"RECRUITMENT, STAFFING AND EMPLOYMENT PLACEMENT",3. Negative,2181.17,f.Easy,Main Banked,217,ETB,0,d.Class 4
2,3,202204,1,0,adcorp wokforce solutions,NaN,BUSINESS AND ADMINISTRATIVE,"RECRUITMENT, STAFFING AND EMPLOYMENT PLACEMENT",3. Negative,5509.40,f.Easy,Main Banked,35,NTB,0,d.Class 4
3,4,202204,1,0,adcorp wokforce solutions,NaN,BUSINESS AND ADMINISTRATIVE,"RECRUITMENT, STAFFING AND EMPLOYMENT PLACEMENT",3. Negative,5054.00,f.Easy,Main Banked,170,RTB,0,g.TF
4,5,202204,1,0,adcorp wokforce solutions,NaN,BUSINESS AND ADMINISTRATIVE,"RECRUITMENT, STAFFING AND EMPLOYMENT PLACEMENT",3. Negative,2973.67,f.Easy,Main Banked,336,ETB,0,c.Class 3